version: '3.1'
services:
  db:
    image: postgres
    ports:
      - "5432:5432" #<host_port>:<container_port>
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DBNAME: postgres

  http-server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
